### ISSUE TITLE
Drop all platform-specific toolchains to reduce support effort?

### ISSUE THREAD

**Issue by gebart** [RIOT-OS/riotdocker#16]
Currently the `latest` label in Docker has support for all RIOT platforms, while the `arm`, `msp430` and `avr` labels only have support for those particular platforms. The original intent was to reduce the download size for people only interested in a specific platform, but I realize that it is a hassle to keep the Dockerfiles in sync.

Does anyone use the reduced functionality images or is everyone who is using docker to build RIOT using the full riot/riotbuild:latest image?

**Comment by kaspar030** [comment]
I was wondering if the reduced size is worth the effort the first time I saw the sub directories.
+1 for dropping them.

**Comment by cgundogan** [comment]
Isn't the download process done only once? Every subsequent run of the `Dockerfile` will just use the populated image and skip the whole setup, if `Dockerfile` was not modified.

+1 for dropping
