### ISSUE TITLE
merge Xtensa-ESP code

### ISSUE THREAD

**Issue by mcr** [RIOT-OS/riotdocker#205]
@gschorcht  is there a reason that:
https://github.com/gschorcht/riotdocker-Xtensa-ESP/blob/master/Dockerfile 
hasn't been merged into this repo?

(The bigger issue is why are we stuck at the 5.2.0 version of esp-idf, and how do we move forward to 8.4.0)

**Comment by gschorcht** [comment]
Not really clear what the question is. The latest version of [riotdocker](https://github.com/RIOT-OS/riotdocker) already includes gcc 8.4.0 for ESP32 SoCs which is compatible with latest versions of ESP-IDF.

**Comment by mcr** [comment]
Never mind.  I see that the main Dockerfile uses and has 8.4.0.
