### ISSUE TITLE
Use docker for CI builds

### ISSUE THREAD

**Issue by Janfred** [RIOT-OS/riotdocker#27]
In a university project I want to set up a CI environment for RIOT with rust support.
I've already changed the Dockerfile in my private project to support rust, but I'm now stuck at setting up the Gitlab-CI-Runner we use at our university.

The main problem is, that the ci-runner is running the commands as root. In your entrypoint run.sh you have a `create_user` which creates a user with the current username (where I'm not pretty sure why a user without a passwd entry can exist, but I haven't completely understood docker yet.)
In my case I have the problem, that the create_user either tells me `useradd: UID 0 is not unique` or (if I try execute `create_user` before) `useradd: user 'riotbuild' already exists` when I want to start the test script.

Do you have any ideas what I could do and explain to me why you need to create a user before?

I've already started some tests with my rust-addons, but I've always used the commandline start.

**Comment by kaspar030** [comment]
> The main problem is, that the ci-runner is running the commands as root.

Can you change that? (Add "-u <other_id>" to 'docker run' command line...)

> In your entrypoint run.sh you have a |create_user| which creates a user
> with the current username (where I'm not pretty sure why a user without
> a passwd entry can exist, but I haven't completely understood docker yet.)

A process can be started with a uid regardless of it existing in passwd.
That's unrelated to Docker.

> In my case I have the problem, that the create_user either tells me
> |useradd: UID 0 is not unique| or (if I try execute |create_user|
> before) |useradd: user 'riotbuild' already exists| when I want to start
> the test script.
> 
> Do you have any ideas what I could do and explain to me why you need to
> create a user before?

If you absolutely cannot run your CI command with a differnt UID than 0,
you'll need to make the useradd command conditional (e.g., ```if [ "$(id
-u)" != 0 ]; then ...``` in run.sh.

The reason we're creating the user is that the docker container allows
building from a host system folder, but inside the container
(```BUILD_IN_DOCKER=1 make ..```). That means the needs to be able to
access the host user's files. In order not to have the files created by
the build process be owned by root, we execute make with the host user's
uid. Problem is that e.g., ssh and git fail if the calling user doesn't
exist. Our workaround is to just create the user entry in the
container's passwd.

(Also, there's a slight increase in security if the build process is not
run as root.)

**Comment by Janfred** [comment]
> If you absolutely cannot run your CI command with a differnt UID than 0, you'll need to make the useradd command conditional (e.g., ```if [ "$(id -u)" != 0 ]; then ...``` in run.sh.

Correct me if I'm wrong but there aren't there more uid's then 0 who have a user assigned in `/etc/passwd`?

I think it would be generally a good idea to insert this check upstream and check if the id the process is currently running under already exists (not just if it is root who executes the docker run).

**Comment by kaspar030** [comment]
> Correct me if I'm wrong but there aren't there more uid's then 0 who have a user assigned in /etc/passwd?

Yes, but we cannot anticipate which uid a user of the container will use.

> I think it would be generally a good idea to insert this check upstream and check if the id the process is currently running under already exists (not just if it is root who executes the docker run).

Yup. Probably just ignoring any error would do the trick. Care to PR a solution of your choice?

**Comment by cladmi** [comment]
I think this can be close as #28 got merged. Please re-open if it is not the case.
