### ISSUE TITLE
MIPS link is broken

### ISSUE THREAD

**Issue by jia200x** [RIOT-OS/riotdocker#46]
I'm trying to rebuild the Docker image and just realized this MIPS package is broken:

http://codescape-mips-sdk.imgtec.com/components/toolchain/2016.05-03/Codescape.GNU.Tools.Package.2016.05-03.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz

That fails the image build

**Comment by gebart** [comment]
See if this works better: http://codescape.mips.com/components/toolchain/2017.10-07/Codescape.GNU.Tools.Package.2017.10-07.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz

**Comment by jia200x** [comment]
yes, that does the trick. I will psuh a fix. Thanks

**Comment by cladmi** [comment]
I am testing a full rebuild now that #46 is merged and will close if it succeeds.

**Comment by cladmi** [comment]
I successfully built the `master` branch so I will close this issue.

**Comment by FlorianHeigl** [comment]
in case you see this, do you happen to still have this SDK someplace? I'm trying to archive all the MIPS SDK stuff, was mostly after Cavium but just found this is also important.

I can track that there were at least those two:
- Codescape.GNU.Tools.Package.2016.05-03.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz
- Codescape.GNU.Tools.Package.2019.09-01.for.MIPS.MTI.Bare.Metal.CentOS-6.x86_64.tar.gz

**Comment by crasbe** [comment]
We *just* removed the the MIPS Toolchain the other day, but the link in the Dockerfile was still working: https://github.com/RIOT-OS/riotdocker/pull/263

Perhaps you can use it to find your versions?

**Comment by FlorianHeigl** [comment]
Hi! So cool you replied!

I was lucky with the downloads, just came to say "found it". I'll leave a list here if it's ok, just for the next person.
Cannot praise Imagination enough for keeping the download links functional even when the main pages were removed. That is a good stewardship of products, it literally just takes one manager who cares to keep this online over website relaunches and they have one. exemplary.


Links I found:

- https://cloud.maschath.de/s/dDrZN4DSgJ33E3w/download/Codescape.GNU.Tools.Package.2019.09-03-2.for.MIPS32.MTI.Bare.Metal.Ubuntu-18.04.5.x86_64.tar.gz
- https://cloud.maschath.de/s/aLtJ86KbXmTm6iE/download/Codescape.GNU.Tools.Package.2019.09-03.for.MIPS32.MTI.Bare.Metal.Ubuntu-18.04.5.x86_64.tar.gz
- https://codescape.mips.com/components/toolchain/2017.10-07/Codescape.GNU.Tools.Package.2017.10-07.for.MIPS.MTI.Bare.Metal.CentOS-5.x86_64.tar.gz
- https://codescape.mips.com/components/toolchain/2020.06-01/Codescape.GNU.Tools.Package.2020.06-01.for.MIPS.MTI.Bare.Metal.CentOS-6.x86_64.tar.gz

It looks like one can still poke around with the filenames and get more but I'll leave it at this for now.

edit: there's a download portal at the following URL
https://codescape.mips.com/components/toolchain/2024.10-03/downloads.html
From 2024 it reaches back till 2016, earlier links are broken.

**Comment by crasbe** [comment]
Sure, glad I could help :)

**Comment by FlorianHeigl** [comment]
@crasbe oh wow, RIOT-OS is a proper RTOS? all power to you! & bye
