### ISSUE TITLE
docker registry not in sync with github

### ISSUE THREAD

**Issue by phiros** [RIOT-OS/riotdocker#6]
When you compare the Dockerfile on https://registry.hub.docker.com/u/riot/riotbuild/dockerfile/
and the one here in the repo you will notice that ```parallel``` is missing in the docker registry version of the Dockerfile. Even worse if you do a:
```docker pull riot/riotbuild```
you end up with an obsolete image (which does not come with ```parallel```):
```
# docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
riot/riotbuild      latest              ca4b323c185b        4 weeks ago         1.44 GB
```
I have no idea what the cause of this is (I always thought that the docker registry keeps itself in sync
with github...).

**Comment by gebart** [comment]
You are right, we don't have the proper webhooks installed in this github repository to trigger builds on Docker Hub. I don't have the proper access to the Github RIOT organisation to fix this, @OlegHahm might be able to help here?

**Comment by gebart** [comment]
Someone in the Owners group has to add the Docker service hook to this repository. https://docs.docker.com/docker-hub/builds/#auto-builds-and-limited-linked-github-accounts

**Comment by gebart** [comment]
@phiros Anyway, I triggered a build manually on the Docker registry page, it is finished now and should be available as `docker pull riot/riotbuild`

**Comment by kaspar030** [comment]
> Someone in the Owners group has to add the Docker service hook to this repository.

Did it. can you test somehow?

**Comment by gebart** [comment]
I will test by pushing a no-op commit to master

**Comment by gebart** [comment]
It worked!
I have reset the master back to delete my nonsense commit, I assume no one based any branches off the master in the meantime.
