### ISSUE TITLE
Docker build is broken

### ISSUE THREAD

**Issue by aabadie** [RIOT-OS/riotdocker#60]
Daily cron jobs are configured on Travis and they are reporting a build failure of the Docker image. See the output of the [last failure](https://travis-ci.org/RIOT-OS/riotdocker/builds/452898067).

There's something wrong with that line:
```
Step 12/26 : RUN wget -q https://sgp.mirror.pkgbuild.com/core/os/x86_64/flex-2.6.4-1-x86_64.pkg.tar.xz -O-         | tar -C / -xJ usr/lib/libfl.so.2.0.0
 ---> Running in d8fec91482a9
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
The command '/bin/sh -c wget -q https://sgp.mirror.pkgbuild.com/core/os/x86_64/flex-2.6.4-1-x86_64.pkg.tar.xz -O-         | tar -C / -xJ usr/lib/libfl.so.2.0.0' returned a non-zero code: 2
```

**Comment by maribu** [comment]
Hi,

> There's something wrong with that line:
> Step 12/26 : RUN wget -q https://sgp.mirror.pkgbuild.com/core/os/x86_64/flex-2.6.4-1-x86_64.pkg.tar.xz -O-         | tar -C / -xJ usr/lib/libfl.so.2.0.0


the link is broken. Replacing it with
http://sgp.mirror.pkgbuild.com/core/os/x86_64/flex-2.6.4-2-x86_64.pkg.tar.xz
could work.

(Please note the version changed 2.6.4-1 to 2.6.4-2)

Kind regards,
Marian
